### ISSUE TITLE
Linkout to blog post

### ISSUE THREAD

**Issue by michaeldupuisjr** [linstula/ember-page-object#21]
@linstula I would link out to [your blog post](https://dockyard.com/blog/2015/09/25/ember-best-practices-acceptance-tests) in the README. It provides some good, introductory context that is not provided in the README.

**Comment by linstula** [comment]
Thanks, @michaeldupuisjr  -  added this as part or the readme update in this PR #24

**Comment by linstula** [comment]
I'm also adding a more explicit link at the top of the readme in #27. Good suggestion :+1:
