### ISSUE TITLE
Sending page-object in vendor bundle?

### ISSUE THREAD

**Issue by mattmcmanus** [linstula/ember-page-object#22]
I hope this isn't a really stupid question. All of the addon's code is in the `/addon` dir. Doesn't that mean that this is being compiled into vendor? Since this is only for testing, wouldn't putting in a place like `/lib` work?

**Comment by linstula** [comment]
This should be resolved by #28. Thanks for raising the issue!

Note the version bump to 1.1.0 and the new relative import path for the core Page Object.

Old import: `import PageObject from 'ember-page-object';`
New import: `import PageObject from '../page-object';`

The core Page Object lives at `tests/page-object` so, you'll have to adjust the path accordingly depending on where you import to.

**Comment by mattmcmanus** [comment]
Super! Glad to help. If I had clear sense of the best way to fix it I would of made  PR. 

Love this library Lin. Makes testing a pleasure.
